In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

I0000 00:00:1788846771.457429   13096 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1788846771.459976   13096 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1788846771.747648   13096 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1788846773.105305   13096 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:0

In [3]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical

In [4]:
wine = load_wine()

In [5]:
X = wine.data
y = wine.target

In [6]:
X.shape

(178, 13)

In [7]:
y.shape

(178,)

6.1 Examine the Dataset

In [8]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [9]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [13]:
X[:5]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
        3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.437e+01, 1.950e+00, 2.500e+00, 1.680e+01, 1.130e+02, 3.850e+00,
        3.490e+00, 2.400e-01, 2.180e+00, 7.800e+00, 8.600e-01, 3.450e+00,
        1.480e+03],
       [1.324e+01, 2.590e+00, 2.870e+00, 2.100e+01, 1.180e+02, 2.800e+00,
        2.690e+00, 3.900e-01, 1.820e+00, 4.320e+00, 1.040e+00, 2.930e+00,
        7.350e+02]])

In [14]:
y[:5]

array([0, 0, 0, 0, 0])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
X,y,test_size=0.20,random_state=42,stratify=y)

In [16]:
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 142
Testing samples: 36


Step 4 — Feature Scaling

In [17]:
scaler=StandardScaler()

In [18]:
X_train_scaled=scaler.fit_transform(X_train)

In [34]:
X_test_scaled=scaler.transform(X_test)

In [35]:
print("Before scaling:")
print(X_train[0])

Before scaling:
[1.328e+01 1.640e+00 2.840e+00 1.550e+01 1.100e+02 2.600e+00 2.680e+00
 3.400e-01 1.360e+00 4.600e+00 1.090e+00 2.780e+00 8.800e+02]


In [36]:
print("\nAfter scaling:")
print(X_train_scaled[0])


After scaling:
[ 0.38580089 -0.63787118  1.77666817 -1.22453161  0.69643032  0.52686525
  0.73229212 -0.1695489  -0.41578344 -0.16746725  0.62437819  0.2529082
  0.46772474]


Exercise 2

In [37]:
print(X_train[0])

[1.328e+01 1.640e+00 2.840e+00 1.550e+01 1.100e+02 2.600e+00 2.680e+00
 3.400e-01 1.360e+00 4.600e+00 1.090e+00 2.780e+00 8.800e+02]


In [38]:
print(X_train_scaled[0])

[ 0.38580089 -0.63787118  1.77666817 -1.22453161  0.69643032  0.52686525
  0.73229212 -0.1695489  -0.41578344 -0.16746725  0.62437819  0.2529082
  0.46772474]


In [39]:
y_train_encoded = to_categorical(y_train, num_classes=3)

In [40]:
y_test_encoded = to_categorical(y_test, num_classes=3)

In [41]:
print("Original labels:")
print(y_train[:5])
print("\nEncoded labels:")
print(y_train_encoded[:5])

Original labels:
[0 0 0 0 2]

Encoded labels:
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [42]:
model=tf.keras.Sequential(
    [
        tf.keras.Input(shape=(13,)),
        tf.keras.layers.Dense(16,activation="relu"),
        tf.keras.layers.Dense(8,activation="relu"),
        tf.keras.layers.Dense(3,activation="softmax")
    ]
)

In [43]:
def create_model(activation="relu", optimizer="adam"):
    model = tf.keras.Sequential([
    tf.keras.Input(shape=(13,)),
    tf.keras.layers.Dense(
    16,
    activation=activation
    ),
    tf.keras.layers.Dense(
    8,
    activation=activation
    ),
    tf.keras.layers.Dense(
    3,
    activation="softmax"
    )
    ])
    model.compile(
    optimizer=optimizer,
    loss="categorical_crossentropy",
    metrics=["accuracy"]
    )
    return model

Activation = ReLU,
Optimizer = Adam

In [44]:
model = create_model(
activation="relu",
optimizer="adam"
)

In [45]:
history = model.fit(
X_train_scaled,
y_train_encoded,
epochs=30,
validation_split=0.2,
verbose=1
)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.2566 - loss: 1.3494 - val_accuracy: 0.2414 - val_loss: 1.2955
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3097 - loss: 1.3005 - val_accuracy: 0.2759 - val_loss: 1.2498
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3451 - loss: 1.2534 - val_accuracy: 0.3103 - val_loss: 1.2079
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3451 - loss: 1.2110 - val_accuracy: 0.3103 - val_loss: 1.1711
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3540 - loss: 1.1741 - val_accuracy: 0.3103 - val_loss: 1.1347
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3540 - loss: 1.1403 - val_accuracy: 0.3793 - val_loss: 1.1024
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3628 - loss: 1.1080 - val_accuracy: 0.4138 - val_loss: 1.0717
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3894 - loss: 1.0808 - val_accuracy: 0.4483 - val_loss: 1.0416


In [46]:
test_loss, test_accuracy = model.evaluate(
X_test_scaled,
y_test_encoded,
verbose=0)

In [47]:
print("Test Accuracy:", test_accuracy)

Test Accuracy: 0.8888888955116272


In [48]:
activations = ["relu", "tanh", "sigmoid"]

In [49]:
results = []

In [51]:
for activation in activations:
    model = create_model(
    activation=activation,
    optimizer="adam"
    )
    
    history = model.fit(
    X_train_scaled,
    y_train_encoded,
    epochs=30,
    validation_split=0.2,
    verbose=0
    )
    
    loss, accuracy = model.evaluate(
    X_test_scaled,
    y_test_encoded,
    verbose=0
    )
    
    results.append([
    activation,
    accuracy
    ])

In [52]:
print("Activation Function | Test Accuracy")
for result in results:
    print(result[0], "|", result[1]) 

Activation Function | Test Accuracy
relu | 0.9722222089767456
tanh | 0.8888888955116272
sigmoid | 0.6944444179534912


Compare Optimizers

In [54]:
optimizers = ["sgd", "adam", "rmsprop"]
optimizer_results = []

In [55]:
for optimizer in optimizers:
    model = create_model(
    activation="relu",
    optimizer=optimizer
    )


    history = model.fit(X_train_scaled,
        y_train_encoded,
        epochs=30,
        validation_split=0.2,
        verbose=0
        )
    loss, accuracy = model.evaluate(
    X_test_scaled,
    y_test_encoded,
    verbose=0
    )
    optimizer_results.append([
    optimizer,
    accuracy
    ])


In [56]:
print("Optimizer | Test Accuracy")
for result in optimizer_results:
    print(result[0], "|", result[1])

Optimizer | Test Accuracy
sgd | 0.7222222089767456
adam | 0.6666666865348816
rmsprop | 0.9722222089767456


In [57]:
optimizers = ["sgd", "adam", "rmsprop"]
activations = ["relu", "tanh", "sigmoid"]
results = []

In [61]:
for optimizer in optimizers:
    for activation in activations:
        model = create_model(
        activation=activation,
        optimizer=optimizer
        )


        history = model.fit(X_train_scaled,
            y_train_encoded,
            epochs=30,
            validation_split=0.2,
            verbose=0
            )
        
        loss, accuracy = model.evaluate(
        X_test_scaled,
        y_test_encoded,
        verbose=0
        )
        
        results.append([
        optimizer,
        activation,
        accuracy
        ])


In [62]:
print("Optimizer | Activation |Test Accuracy")
print("-" * 45)
for result in results:
    print(result[0], "|", result[1], result[2])

Optimizer | Activation |Test Accuracy
---------------------------------------------
sgd | relu 0.8055555820465088
sgd | tanh 0.8888888955116272
sgd | sigmoid 0.2222222238779068
adam | relu 0.8055555820465088
adam | tanh 0.9444444179534912
adam | sigmoid 0.7222222089767456
rmsprop | relu 0.9722222089767456
rmsprop | tanh 0.8888888955116272
rmsprop | sigmoid 0.7222222089767456
